version: "2.4"
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.4
    restart: always
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - 8515:8515
    environment:
      - TZ
      - "LS_JAVA_OPTS=-Xms1g -Xmx1g"
